In [1]:
import pandas as pd

In [14]:
# 1. Create a DataFrame for the 201908-citibike-tripdata data. 
citi_bike_df = pd.read_csv('201908-citibike-tripdata.csv')

In [18]:
# 2. Check the datatypes of your columns. 
citi_bike_df.sample(10)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
1532167,1521,2019-08-20 21:40:01.0270,2019-08-20 22:05:22.7630,3758.0,George St & Wilson Ave,40.702997,-73.929970,471.0,Grand St & Havemeyer St,40.712868,-73.956981,20085,Subscriber,1971,0
1164211,1498,2019-08-16 00:04:06.2800,2019-08-16 00:29:04.8750,72.0,W 52 St & 11 Ave,40.767272,-73.993929,303.0,Mercer St & Spring St,40.723627,-73.999496,16155,Subscriber,1966,1
919199,1067,2019-08-12 20:12:22.9340,2019-08-12 20:30:10.0380,477.0,W 41 St & 8 Ave,40.756405,-73.990026,3156.0,E 72 St & York Ave,40.766638,-73.953483,39889,Subscriber,1988,1
118863,546,2019-08-02 12:56:23.3190,2019-08-02 13:05:29.7190,3493.0,E 118 St & 3 Ave,40.799139,-73.938915,3534.0,Frederick Douglass Blvd & W 117 St,40.805159,-73.954692,33661,Customer,1992,1
90240,79,2019-08-02 05:54:03.2840,2019-08-02 05:55:22.8540,3370.0,E 78 St & 2 Ave,40.772797,-73.955778,3370.0,E 78 St & 2 Ave,40.772797,-73.955778,31004,Subscriber,1960,1
1919069,682,2019-08-26 12:14:45.3100,2019-08-26 12:26:08.2820,327.0,Vesey Pl & River Terrace,40.715338,-74.016584,355.0,Bayard St & Baxter St,40.716021,-73.999744,29950,Subscriber,1989,1
481056,582,2019-08-07 05:49:35.3450,2019-08-07 05:59:17.3610,350.0,Clinton St & Grand St,40.715595,-73.987030,355.0,Bayard St & Baxter St,40.716021,-73.999744,28457,Customer,1969,0
1627831,999,2019-08-22 09:28:27.9380,2019-08-22 09:45:07.1970,3226.0,W 82 St & Central Park West,40.782750,-73.971370,3336.0,E 97 St & Madison Ave,40.787801,-73.953559,27366,Subscriber,1975,2
2189666,274,2019-08-29 19:27:18.0370,2019-08-29 19:31:52.7560,3356.0,Amsterdam Ave & W 66 St,40.774667,-73.984706,3164.0,Columbus Ave & W 72 St,40.777057,-73.978985,39390,Subscriber,1981,2
1830957,190,2019-08-25 10:27:13.7910,2019-08-25 10:30:24.6810,3226.0,W 82 St & Central Park West,40.782750,-73.971370,3161.0,W 76 St & Columbus Ave,40.780184,-73.977285,17398,Subscriber,1888,1

In [22]:
# 3. Convert the 'tripduration' column to datetime datatype.

citi_bike_df['tripduration'] = pd.to_datetime(citi_bike_df['tripduration'], unit='s', infer_datetime_format=True)
citi_bike_df.head(1)

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,1970-01-01 00:06:33,2019-08-01 00:00:01.4680,2019-08-01 00:06:35.3780,531.0,Forsyth St & Broome St,40.718939,-73.992663,408.0,Market St & Cherry St,40.710762,-73.994004,35305,Subscriber,1996,2

In [23]:
# 5. Export the Dataframe as a new CSV file without the index.
citi_bike_df.to_csv(r'C:\Users\josep\Documents\GitHub\bikesharing\NYC_Citibike_tripduration.csv', index=False)